---
- name: Download etcd binary
  get_url:
    url: "https://github.com/etcd-io/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
    dest: "/tmp/etcd.tar.gz"
    mode: '0644'

- name: Extract etcd binary
  unarchive:
    src: "/tmp/etcd.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: yes
    extra_opts:
      - --strip-components=1

- name: Create etcd directories
  file:
    path: "{{ item }}"
    state: directory
    owner: etcd
    group: etcd
    mode: '0755'
  loop:
    - "{{ etcd_data_dir }}"
    - "{{ etcd_config_dir }}"

- name: Ensure etcd SSL directory exists on all nodes
  file:
    path: "{{ remote_cert_dir }}"
    state: directory
    mode: 0755

- name: Generate etcd configuration
  template:
    src: etcd.conf.yml.j2
    dest: "{{ etcd_config_dir }}/etcd.conf.yml"
    owner: etcd
    group: etcd
    mode: '0644'
  notify: Restart etcd

- name: Create etcd systemd service
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: '0644'
  notify: Restart etcd

- name: Update /etc/hosts with etcd_nodes
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.name }}"
    regexp: "^{{ item.ip }}\\s"
    state: present
    create: yes
  loop: "{{ etcd_nodes }}"

- name: Reload systemd and enable etcd
  systemd:
    daemon_reload: true
    name: etcd
    enabled: true
    state: started

- name: Sleep for 5 seconds
  pause:
    seconds: 5
