etcd_nodes:
  - name: ip-10-0-1-222
    ip: 10.0.1.222
  - name: ip-10-0-1-180
    ip: 10.0.1.180
  - name: ip-10-0-1-230
    ip: 10.0.1.230

cert_dir: "/tmp/etcd-certs"
remote_cert_dir: "/etc/etcd/ssl"

etcd_ca_cert: "{{ remote_cert_dir }}/ca.pem"
etcd_server_cert: "{{ remote_cert_dir }}/{{ inventory_hostname }}.pem"
etcd_server_key: "{{ remote_cert_dir }}/{{ inventory_hostname }}-key.pem"
etcd_peer_cert: "{{ remote_cert_dir }}/{{ inventory_hostname }}-peer.pem"
etcd_peer_key: "{{ remote_cert_dir }}/{{ inventory_hostname }}-peer-key.pem"
